# Generated by Django 4.2.4 on 2023-08-16 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, null=True, verbose_name='number')),
                ('name', models.TextField(default='', null=True, verbose_name='medicine_name')),
                ('classification', models.TextField(default='', null=True, verbose_name='medi_classification')),
                ('Ingredients_amount', models.TextField(default='', null=True, verbose_name='Ingredients_amount')),
                ('efficacy', models.TextField(null=True, verbose_name='efficacy')),
                ('infomation', models.TextField(default='', null=True, verbose_name='infomation')),
                ('warning', models.TextField(default='', null=True, verbose_name='warning')),
                ('storage', models.TextField(default='', null=True, verbose_name='storage')),
                ('doping', models.TextField(default='', null=True, verbose_name='doping')),
                ('usage', models.TextField(default='', null=True, verbose_name='usage')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to='posts.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
