# Generated by Django 4.2.4 on 2023-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='medicine',
        ),
        migrations.AddField(
            model_name='scrap',
            name='medi_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrap',
            name='medi_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
