# Generated by Django 4.2.4 on 2023-08-16 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_remove_scrap_medicine_scrap_medi_id_scrap_medi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
