# Generated by Django 4.2.4 on 2023-08-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_scrap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='user_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='user email'),
        ),
    ]
