# Generated by Django 4.2.4 on 2023-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usertakenmedi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertakenmedi',
            name='medi_id',
            field=models.IntegerField(default=0),
        ),
    ]
